version: '3.8'

name: room

services:
  app:
    build: .
    container_name: room-app
    restart: always
    ports:
      - "127.0.0.1:11000:11000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - room-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # ports:
    #  - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - room-net

volumes:
  db_data:


networks:
  room-net:
    driver: bridge