version: '3.8'

services:
  app:
    build: .
    container_name: room-app
    restart: always
    ports:
      - "11000:11000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # ports:
    #  - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
